name: bip340
version: 0.1.0
description: >-
  BIP340 (Schnorr) signature and verification.
repository: https://github.com/fiatjaf/dart-bip340

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  convert: ^3.0.1
  pointycastle: ^3.3.4

dev_dependencies:
  http: ^0.13.3
  csv: ^5.0.0
  test: ^1.21.4
