name: bip340
version: 0.3.0
description: >-
  BIP340 (Schnorr) signature and verification.
repository: https://github.com/fiatjaf/dart-bip340

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  crypto: ^3.0.6
  pointycastle: ^4.0.0

dev_dependencies:
  http: ^1.5.0
  csv: ^6.0.0
  test: ^1.26.3
